In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('C:/Users/MY LENOVO/Desktop/taxi.csv')
data.head()

Priceperweek  Population  Monthlyincome  Averageparkingpermonth  \
0            15     1800000           5800                      50   
1            15     1790000           6200                      50   
2            15     1780000           6400                      60   
3            25     1778000           6500                      60   
4            25     1750000           6550                      60   

   Numberofweeklyriders  
0                192000  
1                190400  
2                191200  
3                177600  
4                176800

In [3]:
data_x = data.iloc[:,0:-1].values
data_y = data.iloc[:,-1].values

In [5]:
len(data_x)

27

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(data_x, data_y, test_size=0.3, random_state=0)

In [8]:
from sklearn.linear_model import LinearRegression

In [10]:
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [11]:
y_pred = reg.predict(X_test)
y_pred

array([188629.50339543, 136559.39301861, 167923.33044203, 126048.35876704,
       178953.09696641, 166223.49873765, 130975.62779069, 167971.3136973 ,
       141866.03727522])

In [12]:
y_test

array([191200, 126080, 160800, 115696, 178400, 163200, 123888, 161600,
       150400], dtype=int64)

In [13]:
print(reg.coef_)

[-5.68775893e+02  1.30158909e-01 -5.49376209e-02  1.22759763e+02]


In [14]:
print(reg.intercept_)

-41535.70104645021


In [16]:
# y = b0 + b1x1 + b2x2 + b3x3 + b4x4
y_0 = reg.intercept_ +reg.coef_[0]*X_test[0][0]+reg.coef_[1]*X_test[0][1]+reg.coef_[2]*X_test[0][2]+reg.coef_[3]*X_test[0][3]
y_1 = reg.intercept_ +reg.coef_[0]*X_test[1][0]+reg.coef_[1]*X_test[1][1]+reg.coef_[2]*X_test[1][2]+reg.coef_[3]*X_test[1][3]
y_1

136559.39301861406

In [18]:
print('Training Score :', reg.score(X_train,y_train)*100)
print('Testing Score :', reg.score(X_test,y_test)*100)

Training Score : 94.28364724316813
Testing Score : 91.57379222488221


In [19]:
z1 = [[80, 1770000, 6500, 80]]
output = reg.predict(z1)
print(output)

[152807.18276596]
